paths:
  /api/products:
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Los productos que fueron cargados satisfactoriamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        "500":
          description: Error interno del Server. Query defectuosa
    post:
      summary: Crear productos
      tags:
        - Products
      responses:
        '405':
          description: Invalid input        
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
  
  /api/products/{pid}:
    get:
      summary: Obtiene el detalle de un solo producto por ID
      tags:
        - Products
      description: Obtener todos los carritos
      operationId: getProductByID
      parameters:
      - name: pid
        in: path
        required: true
        description: ID de la producto que se solicita
        schema:
          type: string
      responses:
        "200":
          description: El producto fue creado satisfactoriamente
        "500":
          description: Error interno del Server. Query defectuosa
        "404":
          description: No se encontro producto por ese ID

    put:
      summary: Modifica algún dato de un solo producto por ID
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: ID de la producto que se solicita
        schema:
          type: string
      responses:
        "200":
          description: El producto fue modificado satisfactoriamente
        "500":
          description: Error interno del Server. Query defectuosa
        "404":
          description: No se encontro producto por ese ID
       
    delete:
      summary: Elimina un solo producto por ID
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: ID de la producto que deseamos eliminar
        schema:
          type: string
      responses:
        "200":
          description: El producto fue eliminado satisfactoriamente
        "500":
          description: Error interno del Server. Query defectuosa
        "404":
          description: No se encontro producto por ese ID

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: ID auto generado por mongo
        title:
          type: string
          description: El nombre del producto
        description:
          type: string
          description: Descripcion del producto
        price:
          type: number
          description: Precio del producto
        thumbnail:
          type: string
          description: Imagen del producto  
        code:
          type: number
          description: Código del producto   
        stock:
          type: number
          description: Stock del producto     
        status:
          type: boolean
          description: Estado del producto  
        category:
          type: string
          description: Categoria del producto  
      example:
        _id: ObjectId("651ad1146448a583a5dd0c7e")
        title: Pc Gamer
        description: PC
        price: 203300
        thumbnail: Array
        code: 400
        stock: 11
        status: true
        category: PC

  requestBodies:
    Product: 
      description: Los productos
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Product'
        application/xml:
          schema:
            $ref: '#/components/schemas/Product'