apiVersion: v1
kind: Service
metadata:
  name: kubservice
spec:
  selector:
    app: kebuappgerman
  ports:
    - port: 8082
    targetPort: 8080
  type: LoadBalancer      


apiVersion: apps/v1
kind: Deployment
metadata:
  name: kebuappgerman
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kebuappgerman
  template:
    metadata:
      labels: 
        app: kebuappgerman      
    spec:
      containers:
        - name: kubecontainers
          image: usuario/usercreator:1.0.0    
          ports:
            - containerPort: 8080
            imagePullPolicy: Always